import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopHeader from "@/components/TopHeader";
import CartHeader from "@/components/CartHeader";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { CartProvider } from "@/app/context/CartContext";
import { WishlistProvider } from "./context/WhishlistContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Comforty Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} mx-auto max-w-[1440px]`}>
      <CartProvider>
        <WishlistProvider>
        <TopHeader />
        <CartHeader />
        <Navbar/>      
            {children}
        </WishlistProvider>     
        </CartProvider>        
        <Footer/>

        <ToastContainer />
        </body>        
    </html>
  );
}
